---
functional:
  - На сайте должна быть система авторизации пользователя.
  - Обеспечена возможность выбора языка программирования в игре.
  - При создании игры пользователем игра отображается в списке доступных для подключения.
  - Пользователям обеспечена возможность присоединения к ранее созданной другим пользователем игре.
  - Создана система матчмейкинга.
  - В игре работает система обмена сообщений (чат).
  - Количество запусков проверки введенного кода не ограничено.
  - Обеспечено отображение кода, набираемого соперником в режиме реального времени.
  - Обеспечена поддержка переподключения при разрыве соединения.
  - Обеспечена поддержка восстановления сессии по ID. 
  - При победе одного из игроков кнопка "Run" у победителя блокируется.
  - При победе одного из игроков победитель не удаляется из игры.
  - При победе одного из игроков у победителя сохраняется функционал просмотра набираемого кода соперника. 
  - Запись игры сохраняется и доступна для просмотра.
  - Существует система рейтингования пользователей.
  - Рейтинг строится за неделю, месяц и все время.
  - Создана возможность переключения языка игры с английского на русский и наоборот.
  - Обеспечено присоединение к игре по ссылке. 
  - Обеспечена возможность выбора пользователем уровня сложности при создании игры с ботом.
non-functional:
  - Отсутствует возможность запуска проверки кода, набранного соперником.
  - Отсутствует таймер на победу - игра идет до определения победителя.
  - При успешном решении задачи одним из игроков отображается модальное окно, извещающее игроков об определении победителя.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
  - Редактор для ввода кода выглядит как проигрыватель.
implicit: 
  - Время игры с ботом ограничено.
  - Должна быть ограничена возможность написания сообщений в чате для неавторизованных пользователей.
  - При переключении языка выполняется перевод управляющих кнопок на язык, соответствующий выбранному пользователем.
  - Управляющие кнопки, отвечающие за выбор уровня сложности игры, отключены при создании игры с пользователем.
  - Создан счетчик времени решения, счетчик отображается пользователю во время игры.


